@startuml
'可視性をアイコン化しない
skinparam classAttributeIconSize 0

'クラスと属性・操作の定義
class main {
  -my_sleep(void): void
  -init(void): void
}

class led {
  +led(int) : void
}


'関連
main --> led
@enduml
